spring.application.name=springRestfull
server.port=8080

# connection db 
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#security config
trinhnguyen.jwtKey=ADhfLiqJtyTrLA9V34FNW7TTBX8WQ1HS6PM8poIugaJuKrIpf6wGPRiEViXhIQWre1v0HRhlr5IimFJSaoim4w==

# Access Token expiration (seconds) - 15 p
trinhnguyen.access-token-expiration=604800

# Refresh Token expiration (seconds) - 7 ng�y
trinhnguyen.refresh-token-expiration=604800

# Max active sessions per user
trinhnguyen.max-active-sessions=5
#version
spring.mvc.servlet.path=/api/v1
#page
spring.data.web.pageable.default-page-size=10

logging.level.org.springframework.security=DEBUG




